### PR TITLE
Enable `dag-jose` decoder

### PR DESCRIPTION
**Pull request by m0ar**
This PR adds support for using the `dag-jose` codec, useful viewing and traversing Ceramic Streams :chains: 

Will solve this issue in `ipfs-webui`: https://github.com/ipfs/ipfs-webui/issues/1912

image

### CODE REVIEW

**Comment by SgtPooki** [comment]
Do you have an example CID we can use to test this out?

**Review by SgtPooki — COMMENTED** [review]
LGTM but i’d love to get a CID to test to confirm

**Comment by SgtPooki** [comment]
Let's also add tests to confirm things continue working properly

**Comment by m0ar** [comment]
@SgtPooki Sorry for the late response, been on vacation :palm_tree: 

Here is a public CID that I pulled from cerscan you can test with: `bagcqcerazgxx3olkiyn3z7osiwx7645un5t7tq3qg66okcv5it2ptlvf2izq`

**Comment by m0ar** [comment]
> Let's also add tests to confirm things continue working properly

@SgtPooki I cannot find any test suite in this package, so I'm not sure how I would go about doing that.

**Comment by SgtPooki** [comment]
> @SgtPooki I cannot find any existing tests in this package, so I'm not sure how I would go about doing that.

@m0ar you know what, you're right.. I believe the tests are in explore.ipld.io and webui :( I would really love to merge explore.ipld.io and this lib into one..

**Review by SgtPooki — APPROVED** [review]

**Pull request merged**
